### ISSUE TITLE
Tool does not build against Opencast > 8.x

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/annotation-tool#325]
Trying to run the tests with the latest Opencast 9 snapshots currently fails the build with the following message:

```
...
[INFO] -------------< org.opencast.annotate:annotation-tool-impl >-------------
[INFO] Building Opencast Annotation Tool :: Backend :: Implementation 2020.0203.143440-f76720a40ec93e5396441131943e1f49a8f02d68 [5/7]
[INFO] -------------------------------[ bundle ]-------------------------------
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.opencast.annotation.endpoint.ExtendedAnnotationsRestServiceTest
log4j:WARN No appenders could be found for logger (com.mchange.v2.log.MLog).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.015 sec <<< FAILURE! - in org.opencast.annotation.endpoint.ExtendedAnnotationsRestServiceTest
org.opencast.annotation.endpoint.ExtendedAnnotationsRestServiceTest  Time elapsed: 2.014 sec  <<< ERROR!
javax.servlet.ServletException: org.glassfish.jersey.servlet.ServletContainer-2bd08376@107b4064==org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=-1,inst=false,async=true
	at org.opencast.annotation.endpoint.ExtendedAnnotationsRestServiceTest.setUp(ExtendedAnnotationsRestServiceTest.java:863)
Caused by: java.lang.IllegalArgumentException
	at org.opencast.annotation.endpoint.ExtendedAnnotationsRestServiceTest.setUp(ExtendedAnnotationsRestServiceTest.java:863)
...
```

This is also responsible for the recent Travis failures.

**Comment by JulianKniephoff** [comment]
I convinced Travis not to use `SNAPSHOT`-versions of Opencast for now (see 63e575df1a029d579d04b2b62bf58adff73d3d7d), but in the long run, we of course need a real fix for this, and then we probably want to revert that commit.

**Comment by JulianKniephoff** [comment]
Now the tool doesn't even build anymore against versions > 8.x. I adapted the `pom.xml` accordingly in 6d112537ba66009283dcaa4e7267916cec3464d7.

**Comment by JulianKniephoff** [comment]
Actually `[7,8+]` is not an okay version range to use according to OSGi. 08a3b25ca43fe41c56bf41ba6a0e4cd5c373d285 fixes that.

We might want to think about why BND doesn't translate it appropriately, though. :thinking:

**Comment by JulianKniephoff** [comment]
Another update on this: f51f480068c5e2307c7c20deee27628ca0c8fffc makes the project work with IntelliJ again, for now.

**Comment by JulianKniephoff** [comment]
> I convinced Travis not to use `SNAPSHOT`-versions of Opencast for now (see [63e575d](https://github.com/opencast/annotation-tool/commit/63e575df1a029d579d04b2b62bf58adff73d3d7d)), but in the long run, we of course need a real fix for this, and then we probably want to revert that commit.

This is reverted in 1ae11db0b614fa4194c4b0953429d65f130ffd9f.

**Comment by JulianKniephoff** [comment]
#458 fixes the build, but tests still don't run with Opencast 9. :disappointed: 

I deactivated them in CI for now, which is a shame.
